"""New Migration

Revision ID: 0112c936a13d
Revises: b21ae260d0ca
Create Date: 2023-02-06 14:10:07.756223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0112c936a13d'
down_revision = 'b21ae260d0ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
