"""New Migration

Revision ID: 1bd67dc9e585
Revises: 9fec42ff046f
Create Date: 2023-02-06 15:56:16.714406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bd67dc9e585'
down_revision = '9fec42ff046f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
