"""New Migration

Revision ID: 309f37d4c74c
Revises: ea2a6aa792f7
Create Date: 2023-02-07 16:04:54.841331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '309f37d4c74c'
down_revision = 'ea2a6aa792f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('web_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'city', ['web_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'city', type_='unique')
    op.drop_column('city', 'web_id')
    # ### end Alembic commands ###
