"""New Migration

Revision ID: 30bdfbd149b7
Revises: ec424ecef67c
Create Date: 2023-02-08 18:01:10.173655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30bdfbd149b7'
down_revision = 'ec424ecef67c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
