"""New Migration

Revision ID: 3ce2d1285b00
Revises: 4cc8c80c8420
Create Date: 2023-02-06 17:27:10.007796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ce2d1285b00'
down_revision = '4cc8c80c8420'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('city', 'randon_field')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('randon_field', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
