"""New Migration

Revision ID: 3e0bb593cf79
Revises: a416faa505b9
Create Date: 2023-02-06 18:28:56.620731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e0bb593cf79'
down_revision = 'a416faa505b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
