"""New Migration

Revision ID: 5921dfc2b73d
Revises: 3e0bb593cf79
Create Date: 2023-02-06 19:04:56.720995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5921dfc2b73d'
down_revision = '3e0bb593cf79'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather', sa.Column('time_stamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weather', 'time_stamp')
    # ### end Alembic commands ###
