"""New Migration

Revision ID: 9edefe486a7e
Revises: 628a1e4c60fe
Create Date: 2023-02-06 15:43:06.316713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9edefe486a7e'
down_revision = '628a1e4c60fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
