"""New Migration

Revision ID: 9fec42ff046f
Revises: 9edefe486a7e
Create Date: 2023-02-06 15:53:41.792177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fec42ff046f'
down_revision = '9edefe486a7e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
