"""New Migration

Revision ID: a416faa505b9
Revises: 3ce2d1285b00
Create Date: 2023-02-06 18:19:09.530542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a416faa505b9'
down_revision = '3ce2d1285b00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
