"""New Migration

Revision ID: e26afc3fd5c0
Revises: 5921dfc2b73d
Create Date: 2023-02-06 19:26:18.766894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e26afc3fd5c0'
down_revision = '5921dfc2b73d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
