"""New Migration

Revision ID: ec424ecef67c
Revises: 309f37d4c74c
Create Date: 2023-02-07 16:19:58.760776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec424ecef67c'
down_revision = '309f37d4c74c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
